export {
  resourceTypeSchema,
  platformSchema,
  transcriptSourceSchema,
  transcriptStatusSchema,
  resourceSchema,
  transcriptSegmentSchema,
  transcriptSchema,
  extractionJobStatusSchema,
  extractionJobKindSchema,
  extractionJobSchema,
  transcriptCursorPayloadSchema,
  type ResourceType,
  type Platform,
  type TranscriptSource,
  type Resource,
  type TranscriptSegment,
  type Transcript,
  type ExtractionJobStatus,
  type ExtractionJobKind,
  type ExtractionJob,
  type TranscriptCursorPayload,
} from "./domain.js";
